

[normalized]
[normalized.match]
title = 20
content = 1
source = 40
[normalized.mismatch]
title = -20
content = -20
source = -10


[raw]
[raw.match]
title = 2
content = 1
source = 2
date = 9
[raw.mismatch]
title = -5
content = -10
source = 0
date = 0
