# Generated by Django 4.1.7 on 2023-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_article_tags_alter_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarytags',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='pri_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='sec_tags',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PrimaryTags',
        ),
        migrations.DeleteModel(
            name='SecondaryTags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
